---
title: "Premier Leage Stadia"
author: "Andrew Laws"
date: '2018-09-09'
output: html_document
---
#### See exactly where all the stadia involved in the 2018/19 premier league are located. 
####Click on a logo to see a link to the wikipedia entry for each stadium.
```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(leaflet)
```

```{r, echo=FALSE}
lat <- c(51.555, 50.735278, 50.861822, 53.789167, 51.472778, 51.481667, 51.398333, 53.438889, 51.475, 53.654167, 52.620278, 53.430833, 53.483056, 53.463056, 54.975556, 50.905833, 51.603333, 51.65, 51.538611, 52.590278)
lng <- c(-0.108611, -1.838333, -0.083278, -2.230278, -3.203056, -0.191111, -0.085556, -2.966389, -0.221667, -1.768333, -1.142222, -2.960833, -2.200278, -2.291389, -1.621667, -1.391111, -0.065833, -0.401667, -0.016389, -2.130278)
df <- data.frame(lat, lng)
```

```{r, echo=FALSE}
arsIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/4us2nCgl6kgZc0t3hpW75Q_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
bmthIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/IcOt-hrK04B-RlRwI3R0yA_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
btonIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/EKIe0e-ZIphOcfQAwsuEEQ_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
brnlyIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/teLLSaMXim_8BA1d93sMng_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
cdiffIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/mTDxrTqWa4SqI0rCi5LhqA_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
chelsIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/fhBITrIlbQxhVB6IjxUO6Q_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
cryspalIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/8piQOzndGmApKYTcvyN9vA_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
everIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/C3J47ea36cMBc4XPbp9aaA_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
fulhIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/Gh7_5p3n364p4vxeM8FhNg_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
hudIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/Pkhtbw1Npp_vEjxqRSZWwA_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
leicIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/UDYY4FSlty6fXFBzvFfcyw_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
liverIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/0iShHhASp5q1SL4JhtwJiw_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
manuIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/udQ6ns69PctCv143h-GeYw_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
mancIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/z44l-a0W1v5FmgPnemV6Xw_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
newcIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/96CcNNQ0AYDAbssP0V9LuQ_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
shampIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/y1V4sm2SEBiWUPRIYl5rfg_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
tottIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/k3Q_mKE98Dnohrcea0JFgQ_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
watfIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/lHr1L31i7aJS-O8tUdHOIQ_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
westhamIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/bXkiyIzsbDip3x2FFcUU3A_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)
wolvesIcon <- makeIcon(
  iconUrl = "https://ssl.gstatic.com/onebox/media/sports/logos/-WjHLbBIQO9xE2e2MW3OPQ_48x48.png",
  iconWidth = 41*215/230, iconHeight = 41,
  iconAnchorX = 41*215/230, iconAnchorY = 20
)

icons <- iconList(arsIcon, bmthIcon, btonIcon, brnlyIcon, cdiffIcon, chelsIcon, cryspalIcon, everIcon, fulhIcon, hudIcon, leicIcon, liverIcon, mancIcon, manuIcon, newcIcon, shampIcon, tottIcon, watfIcon, westhamIcon, wolvesIcon)

iconSites <- c(
  "<a href='https://en.wikipedia.org/wiki/Emirates_Stadium'>Emirates Stadium</a>",
  "<a href='https://en.wikipedia.org/wiki/Dean_Court'>Dean Court</a>",
  "<a href='https://en.wikipedia.org/wiki/Falmer_Stadium'>Falmer Stadium</a>",
  "<a href='https://en.wikipedia.org/wiki/Turf_Moor'>Turf Moor</a>",
  "<a href='https://en.wikipedia.org/wiki/Cardiff_City_Stadium'>Cardiff City Stadium</a>",
  "<a href='https://en.wikipedia.org/wiki/Stamford_Bridge_(stadium)'>Stamford Bridge</a>",
  "<a href='https://en.wikipedia.org/wiki/Selhurst_Park'>Selhurst Park</a>",
  "<a href='https://en.wikipedia.org/wiki/Goodison_Park'>Goodison Park</a>",
  "<a href='https://en.wikipedia.org/wiki/Craven_Cottage'>Craven Cottage</a>",
  "<a href='https://en.wikipedia.org/wiki/Kirklees_Stadium'>Kirklees Stadium</a>",
  "<a href='https://en.wikipedia.org/wiki/King_Power_Stadium'>King Power Stadium</a>",
  "<a href='https://en.wikipedia.org/wiki/Anfield'>Anfield</a>",
  "<a href='https://en.wikipedia.org/wiki/City_of_Manchester_Stadium'>City of Manchester Stadium</a>",
  "<a href='https://en.wikipedia.org/wiki/Old_Trafford'>Old Trafford</a>",
  "<a href='https://en.wikipedia.org/wiki/St_James%27_Park'>St. James' Park</a>",
  "<a href='https://en.wikipedia.org/wiki/St_Mary%27s_Stadium'>St. Mary's</a>",
  "<a href='https://en.wikipedia.org/wiki/White_Hart_Lane'>White Hart Lane</a>",
  "<a href='https://en.wikipedia.org/wiki/Vicarage_Road'>Vicarage Road</a>",
  "<a href='https://en.wikipedia.org/wiki/London_Stadium'>The London Stadium</a>",
  "<a href='https://en.wikipedia.org/wiki/Molineux_Stadium'>Molineux</a>"
)

df %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(icon = icons, popup = iconSites)
```
